# This is a config for E2B sandbox template.
# You can use template ID (0lfnpv0db3gtxy5104mj) or template name (vibe-nextjs-test-32) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-32") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-32") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-32')

team_id = "92df3810-d6ec-44e7-9f74-fe1250c06cec"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-32"
template_id = "0lfnpv0db3gtxy5104mj"
